version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/next-auth-boilerplate
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=development-jwt-secret-please-change-in-production
      - JWT_REFRESH_SECRET=development-refresh-secret-please-change-in-production
      - EMAIL_SERVER_HOST=maildev
      - EMAIL_SERVER_PORT=1025
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-nextauth-secret
      - TWO_FACTOR_ISSUER=NextAuthBoilerplate
      - TWO_FACTOR_LABEL=NextAuth Account
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
      - redis
      - maildev
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: next-auth-boilerplate
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass devpassword
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - "1080:1080" # Web interface
      - "1025:1025" # SMTP server
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
